#!/usr/bin/perl -w

# mm2s_blacklist - Copy per-list blacklist.
#
#	Author: John Bazik
#
# Copyright 2010 Brown University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib 'lib';

use mmparse;

my $m_cfg;

#
# Load mailman config.
#
{
   local $/=undef;
   $m_cfg = mmparse(<STDIN>);
}

#
# Generate blacklist
#
for my $addr (@{$m_cfg->{ban_list}}) {
   if ($addr =~ /^\^/) {
      print "# $addr\n";	# preserve regex's, but comment them out
   }
   else {
      print "$addr\n";
   }
}
