#!/usr/bin/perl -w

# mm2s_users - Generate a csv of users.
#
#	Author: John Bazik
#
# Copyright 2010 Brown University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib 'lib';

use JSON;

my $m_cfg;

#
# Load mailman config.
#
{
   local $/=undef;
   $m_cfg = decode_json <STDIN>;
}

my %users = map {$_, 1}
		keys %{$m_cfg->{user_options}},
		@{$m_cfg->{accept_these_nonmembers}},
;


for my $user (sort keys %users) {
   my $name = $m_cfg->{usernames}->{$user} || '';
   my $pass = $m_cfg->{passwords}->{$user} || genpw();
   print "$user;$name;$pass\n";
}

sub genpw {
   my $chars = 'abcdefghijkmnpqrstuvwxyz23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
   my $len = length $chars;
   my $password = '';

   for (1..8) {
      $password .= substr($chars, int(rand($len)), 1);
   }
   return $password;
}
