#!/usr/bin/perl -w

# mm2s_admins - Generate a csv of list administrators.
#
#	Author: John Bazik
#
# Copyright 2010 Brown University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib 'lib';

use mmparse;

my $m_cfg;

#
# Load mailman config.
#
{
   local $/=undef;
   $m_cfg = mmparse(<STDIN>);
}

my $list_name = lc($m_cfg->{real_name});

#
# Generate admins
#
for my $owner (@{$m_cfg->{owner}}) {
   print "$owner;owner;$list_name\n"
}
for my $editor (@{$m_cfg->{moderator}}) {
   print "$editor;editor;$list_name\n"
}
